INTERACTIVE_MODELS_PATH: "/ritm_models" # was changed
EXPS_PATH: "/tmp/ritm_training/experiments"

# Evaluation datasets
GRABCUT_PATH: "/datasets/GrabCut" # was changed
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"

# Train datasets
SBD_PATH: "/data/benchmark_RELEASE/dataset"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "./datasets/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "/ritm_models/coco_lvis_h18_itermask.pth"
  HRNETV2_W18_SMALL: "/ritm_models/coco_lvis_h18s_itermask.pth"
  HRNETV2_W32: "/ritm_models/coco_lvis_h32_itermask.pth"
