version: "2.2"
services:
  ritm_training:
    shm_size: '8gb'
    runtime: nvidia
    build:
      context: .
      args:
        IMAGE: supervisely/base-py-sdk:6.4.3
    ports:
      - "9799:22"
    volumes:
      - "./data:/data"